// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Models;

public partial class FileAttach
{
    public int FileId { get; set; }

    public string SystemPath { get; set; }

    public string FileName { get; set; }

    public int FileSize { get; set; }

    public DateTime CreatedBy { get; set; }

    public DateTime CreatedTime { get; set; }

    public virtual ICollection<IssueFormTask> IssueFormTask { get; set; } = new List<IssueFormTask>();
}