// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Models;

public partial class IssueForm
{
    public int FormId { get; set; }

    public string DocNo { get; set; }

    public string SystemStatusCode { get; set; }

    public int? CreatedBy { get; set; }

    public DateTime? CreatedTime { get; set; }

    public DateTime? SubmitedTime { get; set; }

    public DateTime? DoneTime { get; set; }

    public int? ModifiedBy { get; set; }

    public DateTime? ModifiedTime { get; set; }

    public int? ClosedBy { get; set; }

    public DateTime? ClosedTime { get; set; }

    public virtual ICollection<IssueFormTask> IssueFormTask { get; set; } = new List<IssueFormTask>();
}