// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Models;

public partial class IssueFormTask
{
    public int FromId { get; set; }

    public int TaskSeq { get; set; }

    public int? IssueCategoriesId { get; set; }

    public int? ProductId { get; set; }

    public string SystemStatusCode { get; set; }

    public DateTime? CreatedTime { get; set; }

    public DateTime? ModifiedTime { get; set; }

    public int? Br_Qty { get; set; }

    public string Rp_Location { get; set; }

    public int? FileId { get; set; }

    public DateTime? SubmitTime { get; set; }

    public int? AssignedTo { get; set; }

    public DateTime? AssignedTime { get; set; }

    public DateTime? DoneTime { get; set; }

    public string RejectReason { get; set; }

    public virtual FileAttach File { get; set; }

    public virtual IssueForm From { get; set; }

    public virtual Rel_Categories_Product Rel_Categories_Product { get; set; }

    public virtual Ref_TaskStatus SystemStatusCodeNavigation { get; set; }
}