// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Models;

public partial class IssueFormAudit
{
    public int LogId { get; set; }

    public int? FormId { get; set; }

    public string Action { get; set; }

    public DateTime? ActionTime { get; set; }

    public int? ActionBy { get; set; }
}