// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Models;

public partial class IssueFormTaskAudit
{
    public int LogId { get; set; }

    public int FormId { get; set; }

    public string TaskSeq { get; set; }

    public string Action { get; set; }

    public int? ActionBy { get; set; }

    public DateTime? ActionTime { get; set; }

    public int? IssueCategoriesId { get; set; }

    public int? ProductId { get; set; }

    public int? Qty { get; set; }
}