// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Models;

public partial class Ref_FormStatus
{
    public string SystemStatusCode { get; set; }

    public string Descriptions { get; set; }

    public string UserStatusCode { get; set; }

    public virtual ICollection<IssueForm> IssueForm { get; set; } = new List<IssueForm>();
}