// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Models;

public partial class Ref_TaskStatus
{
    public string SystemStatusCode { get; set; }

    public string Description { get; set; }

    public bool? IsDone { get; set; }

    public string UserStatusCode { get; set; }

    public virtual ICollection<IssueFormTask> IssueFormTask { get; set; } = new List<IssueFormTask>();
}