// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Models;

public partial class Rel_Categories_Product
{
    public int IssueCategoriesId { get; set; }

    public int ProductId { get; set; }

    public DateTime CreatedTime { get; set; }

    public virtual IssueCategories IssueCategories { get; set; }

    public virtual ICollection<IssueFormTask> IssueFormTask { get; set; } = new List<IssueFormTask>();

    public virtual Product Product { get; set; }
}