// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Models;

public partial class RunningNo
{
    public int Id { get; set; }

    public string Prefix { get; set; }

    public int? NextNumber { get; set; }

    public DateTime? ModifiedTime { get; set; }

    public string YearMonth { get; set; }
}