// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Models;

public partial class SystemError
{
    public int ErrorId { get; set; }

    public int ErrorBy { get; set; }

    public string ErrorType { get; set; }

    public string ErrorMessage { get; set; }
}