// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Domain.Models
{
    public partial class USP_Query_FormTasksByStatusResult
    {
        public int? FormId { get; set; }
        [StringLength(50)]
        public string DocNo { get; set; }
        public int? TaskSeq { get; set; }
        public int? IssueCategoriesId { get; set; }
        [StringLength(100)]
        public string IssueCategoriesName { get; set; }
        public int? ProductId { get; set; }
        [StringLength(100)]
        public string ProductName { get; set; }
        [StringLength(20)]
        public string SystemStatusCode { get; set; }
        [StringLength(20)]
        public string UserStatusCode { get; set; }
        public DateTime? CreatedTime { get; set; }
        public DateTime? ModifiedTime { get; set; }
        public int? Br_Qty { get; set; }
        [StringLength(100)]
        public string Rp_Location { get; set; }
        public DateTime? DetectedTime { get; set; }
        public int? FileId { get; set; }
        public DateTime? SubmitTime { get; set; }
        public int? AssignedTo { get; set; }
        public DateTime? AssignedTime { get; set; }
        public DateTime? DoneTime { get; set; }
        [StringLength(500)]
        public string RejectReason { get; set; }
        public bool? CanCancelDone { get; set; }
        public int? TotalCount { get; set; }
    }
}
