// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Domain.Models
{
    public partial class USP_Query_TaskLogsResult
    {
        [StringLength(50)]
        public string Username { get; set; }
        [StringLength(50)]
        public string Action { get; set; }
        public DateTime? ActionTime { get; set; }
        public int? TotalCount { get; set; }
    }
}
