// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Domain.Models
{
    public partial class USP_Query_IssueProductResult
    {
        public int ProductId { get; set; }
        [StringLength(512)]
        public string ProductName { get; set; }
        public DateTime CreatedTime { get; set; }
        public DateTime ModifiedTime { get; set; }
        [StringLength(50)]
        public string CategoryName { get; set; }
        public int? TotalCount { get; set; }
    }
}
