// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Domain.Models
{
    public partial class USP_Query_WorkloadSummaryResult
    {
        public int? UserId { get; set; }
        [StringLength(100)]
        public string Username { get; set; }
        public int? CanAssigned { get; set; }
        public int? TotalAssigned { get; set; }
        public int? BorrowSubmit { get; set; }
        public int? BorrowAssigned { get; set; }
        public int? RepairSubmit { get; set; }
        public int? RepairAssigned { get; set; }
        public int? ProgramSubmit { get; set; }
        public int? ProgramAssigned { get; set; }
        public int? TotalCount { get; set; }
    }
}
