// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Domain.Models
{
    public partial class USP_Query_OverallFormsStatusResult
    {
        public int? TotalForm { get; set; }
        public int? DraftedForm { get; set; }
        public int? SubmittedForm { get; set; }
        public int? InProgressForm { get; set; }
        public int? CompletedForm { get; set; }
        public int? TotalCount { get; set; }
    }
}
