// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Domain.Models
{
    public partial class USP_Query_NameResult
    {
        public int? UserId { get; set; }
        [StringLength(50)]
        public string Username { get; set; }
        public int? RoleID { get; set; }
        [StringLength(50)]
        public string RoleName { get; set; }
        public int? TotalCount { get; set; }
    }
}
