// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Domain.Models
{
    public partial class USP_Query_ChartResult
    {
        [StringLength(5)]
        public string Hour { get; set; }
        public int? Submit { get; set; }
        public int? Assigned { get; set; }
        public int? Done { get; set; }
        public int? Closed { get; set; }
    }
}
