// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Domain.Models
{
    public partial class USP_Query_FormTaskDetailResult
    {
        public int? FormId { get; set; }
        public int? TaskSeq { get; set; }
        [StringLength(50)]
        public string IssueCategoriesName { get; set; }
        [StringLength(50)]
        public string ProductName { get; set; }
        public int? Quantity { get; set; }
        [StringLength(50)]
        public string Location { get; set; }
        public DateTime? DetectedTime { get; set; }
        [StringLength(50)]
        public string Status { get; set; }
        public bool? IsProgramIssue { get; set; }
        public int? TotalCount { get; set; }
    }
}
