// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Domain.Models
{
    public partial class USP_Query_CategoriesResult
    {
        public int? IssueCategoriesId { get; set; }
        [StringLength(50)]
        public string IssueCategoriesName { get; set; }
        public bool? IsProgramIssue { get; set; }
        public int? TotalCount { get; set; }
    }
}
